const price = (price) => {
  Number.prototype.format = function (n, x) {
    var re = "\\d(?=(\\d{" + (x || 3) + "})+" + (n > 0 ? "\\." : "$") + ")";
    return this.toFixed(Math.max(0, ~~n)).replace(new RegExp(re, "g"), "$&,");
  };
  return price.format();
};

const listing = [
  {
    id: 1,
    title: "Apartment for rent",
    slug: "apartment-for-rent",
    price: price(50000),
    location: "Nairobi",
    description:
      "Boasting an array of sleek finishes and a thoughtful open plan layout, this immaculate 3-bedroom, 2-bathroom condo is a paradigm of contemporary living. Features of this 531 sq. ft. home include wide plank engineered hardwood floors, huge Pella windows with western exposure, central heating and cooling, and a convenient washer/dryer hook-up. Beyond a functional entryway space the home flows into a luminous, open- concept living, dining, and kitchen area.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Elizabeth Keen",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi Westlands",
      county: "Nairobi",
      city: "Nairobi",
      street: "Tengecha St",
      area: "Nairobi",
    },

    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Apartments",
  },
  {
    id: 2,
    title: "House for Sell",
    slug: "house-for-sell",
    price: price(25000),
    location: "Nakuru",
    description:
      "This 3 Bedroom W/ 2 Full Bathroom Ranch Home Is Immaculate & Full Of Upgrades! Enjoy The Open Floor Plan W/ Vaulted 15ft Ceilings & Large Windows Throughout. The Beautiful Kitchen Is The Heart Of The Home Complete With Large Customized Granite Island & Stainless Steel Appliances. Updated Lighting Throughout The Entire Home. ",
    images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Kevin Caster",
      image: "agent3.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nakuru Westlands",
      county: "Nakuru",
      city: "Nakuru",
      street: "Tenwek street",
      area: "Nakuru",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Offices",
  },
  {
    id: 3,
    title: "Apartment In Nairobi",
    slug: "apartment-in-nairobi",
    price: price(31000),
    location: "Nairobi",
    description:
      "Stunning large late two bedroom contemporary home with soaring ceilings and windows, split levels, great floor plan including open dining and living room. Located in the beautiful hilly and treed, desirable Windmill Hill section of Ngong you are conveniently located to shops, dining, and 20 minutes to downtown Nairobi.",
    images: ["image7.jpg", "image3.jpg", "image2.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Elizabeth Keen",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 2,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi Kilimani",
      county: "Nairobi",
      city: "Nairobi",
      street: "Galana Court",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "Sales",
    category: "Offices",
  },
  {
    id: 4,
    title: "Renovated House For Sale",
    slug: "renoveted-house-for-sale",
    price: price(35000),
    location: "Kisumu",
    description:
      "Perfectly set on a tree-shaded lot, this one bedroom feels like home the minute you pull up. The living room is warm and inviting, centered by a wood-burning fireplace and built-in shelving. A spacious breakfast area looks out to the backyard and flows into the kitchen, where you’ll find a breakfast bar, double oven and built-in cook top. The master bedroom is large with no lack of storage, including a separate walk-in closet and additional dual closets.",
    images: ["image4.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Priscilla Frankson",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 1,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Riati Hills Kisumu",
      county: "Kisumu",
      city: "Kisumu",
      street: "Riati street",
      area: "Kisumu",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Houses",
  },
  {
    id: 5,
    title: "House in Nakuru",
    slug: "house-in-nakuru",
    price: price(35000),
    location: "Nakuru",
    description:
      "Excellent little home superbly located right off Old Nakuru Road!! 3 bedrooms, 2 baths, with a covered back patio. The home also features a water softener, refrigerator, clothes washer, and clothes dryer!!! ",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Joram Davies",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Old Nakuru Road",
      county: "Nakuru",
      city: "Nakuru",
      street: "Tengecha St",
      area: "Nakuru",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Retails",
  },
  {
    id: 6,
    title: "Apartment for rent",
    slug: "apartment-for-rent",
    price: price(35000),
    location: "Nairobi",
    description:
      "This three-bedroom home was built in 2018 by noted local architect Archie Techt, and boasts clean lines and vintage woodwork. Located on the border of Westlands Park, the double lot looks directly into heavily wooded parkland, and your neighbors on either side are screened off by trees.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Kevin Caster",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi Westlands",
      county: "Nairobi",
      city: "Nairobi",
      street: "Crossway",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "rentals",
    category: "Apartments",
  },
  {
    id: 7,
    title: "Offices for rent",
    slug: "offices-for-rent",
    price: price(35000),
    location: "Nairobi",
    description:
      "This luxurious Colonial features impeccable finishes throughout, from beautiful, original hardwood floors, to a gorgeous antique marble fireplace. The updated interiors feature a soft monochromatic palette and clean lines, and outside, the beautiful, landscaped lot is the work of the popular landscape architecture firm Richards Hooper.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Laura Ray",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 4,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi CBD",
      county: "Nairobi",
      city: "Nairobi",
      street: "Old Mutual",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Houses",
  },
  {
    id: 8,
    title: "Apartment for rent",
    slug: "apartmen-for-rent",
    price: price(35000),
    location: "Nairobi",
    description:
      "This fully-renovated brick row home features heart pine hardwood floors and a full smart home system including a Nest thermostat and a Ring doorbell. In the chef’s kitchen, there are stainless steel Bosch appliances, travertine waterfall counters, and a Breville espresso machine. And upstairs, the ensuite master bath features twin Grohe basins.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Elizabeth Keen",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi Ngara",
      county: "Nairobi",
      city: "Nairobi",
      street: "Ngara St",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Houses",
  },
  {
    id: 9,
    title: "Apartment for rent",
    slug: "apartment-for-rent",
    price: price(35000),
    location: "Nairobi",
    description:
      "This four bedroom, five-and-a-half bath mid-century modern offers inspiring spaces and an exceptional amount of outdoor space. The great room features cathedral ceilings, multiple exposures, and a custom chandelier, while the updated kitchen boasts quartz countertops and Wolfe stainless steel appliances, and opens via double doors onto a massive wooden deck that overlooks the backyard koi pond.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Edward Johnson",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 4,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Nairobi Kilimani",
      county: "Nairobi",
      city: "Nairobi",
      street: "Crossroad St",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "rentals",
    category: "Retails",
  },
];

export default listing;
